export const QUERY_KEYS = {
  ACCESS_TOKEN: "ACCESS_TOKEN",
  SEAT_LIST: "SEAT_LIST",
  REVIEW_LIST: "REVIEW_LIST",
  REVIEW: "REVIEW",
  COMMENT_LIST: "COMMENT_LIST",
  NOTIFICATION_LIST: "NOTIFICATION_LIST",
};
